### ISSUE TITLE
pretrained model link -> "This link has been removed."

### ISSUE THREAD

**Issue by 77waiwai-Demon** [nburgdorfer/V-FUSE#1]
Hello, I was trying to download the pretrained model from the link provided in the README, but unfortunately, it appears that the link is no longer active, displaying the message "This link has been removed."

Could you please provide an updated link or alternative way to access the pretrained model? 

Thank you very much for your time and for sharing your work with the community.

**Comment by nburgdorfer** [comment]
The cloud provider I was storing them on is having some issues. I put them on a temporary drive and updated the README. Let me know if you have any issues downloading them.
